#spring.application.name=StudentManagement

spring.application.name=student-management
# Cau hinh file Database SQLite (tu dong tao file student.db tai thu muc goc project)
# spring.datasource.url=jdbc:sqlite:student.db
# spring.datasource.driver-class-name=org.sqlite.JDBC

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# Cau hinh JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true